"""Create Transaction table

Revision ID: 6d75ab92af8b
Revises: 
Create Date: 2024-12-24 11:04:50.877316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d75ab92af8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_category'), 'transaction', ['category'], unique=False)
    op.create_index(op.f('ix_transaction_customer_id'), 'transaction', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_product_id'), 'transaction', ['product_id'], unique=False)
    op.create_index(op.f('ix_transaction_transaction_id'), 'transaction', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_transaction_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_product_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_customer_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_category'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
